name-template: '${{ steps.latest-tag.outputs.latest-tag }}'
template: |
  ## Changes
  base package from https://github.com/cloudflare/cloudflared/releases/tag/${{ steps.latest-tag.outputs.latest-tag }}
