name: Compare Releases
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  # schedule:
  #   - cron:  '*/5 * * * *'
jobs:
  compare-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release info for official cloudflared
        id: official_release
        run: |
          release_info=$(curl https://api.github.com/repos/cloudflare/cloudflared/releases/latest)
          echo "::set-output name=release_name::$(echo $release_info | jq .html_url | sed -n 's/.*\/tag\/\([^"]*\).*/\1/p')"
      - name: Get latest release info for my cloudflared-tunnel
        id: my_release
        run: |
          release_info=$(curl https://api.github.com/repos/Jake-Qu/cloudflared-tunnel/releases/latest)
          echo "::set-output name=release_name::$(echo $release_info | jq .html_url | sed -n 's/.*\/tag\/\([^"]*\).*/\1/p')"
      - name: Compare release names
        run: |
          if [ "${{ steps.official_release.outputs.release_name }}" == "${{ steps.my_release.outputs.release_name }}" ]; then
            echo "The latest releases of the two repositories have the same name."
          else
            echo "The latest releases of the two repositories do not have the same name."
          fi
