# docker-image.yml
name: Publish Docker image   # workflow名称，可以在Github项目主页的【Actions】中看到所有的workflow
on:   # 配置触发workflow的事件
  push:
    tags:       # tag更新时触发此workflow
      - '**'
jobs:  # workflow中的job
  push_to_registry:  # job的名字
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest   # job运行的基础环境
    steps:  # 一个job由一个或多个step组成
      - name: Check out the repo
        uses: actions/checkout@v3   # 官方的action，获取代码
      - name: Set up Docker BuildX  # Docker配置多平台环境
        uses: docker/setup-buildx-action@v2 
      - name: Docker Login
        uses: docker/login-action@v2.1.0  # 三方的action操作， 执行docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0  # 抽取项目信息，主要是镜像的tag
        with:
          images: qubo93/cloudflared-tunnel
      - name: Build and push Docker image for X86_64
        uses: docker/build-push-action@v4.0.0 # docker build & push
        with:
          context: .
          file: ./Dockerfile
          push: true
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # - name: Build and push Docker image for ARM
      #   uses: docker/build-push-action@v4.0.0 # docker build & push
      #   with:
      #     context: .
      #     file: ./Dockerfile_arm
      #     push: true
      #     platforms: |
      #       linux/arm64
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
        
